version: '3.7'

services:
    app:
        build: ./
        command: streamlit run app/main.py --server.port 8000
        volumes:
            - ./:/myapp
        ports:
            - 8080:8080
        image: streamlit-app-demo:latest